# --------------------------------------------------------------------
#
# Build branches. Supports developer controls to skip various parts of
# the build. The following are the recognized keywords. Place anywhere
# within commit message. Multiple controls honored. Not case sensitive.
#
# [skip all]
# [skip compile-both]
# [skip compile-debug]
# [skip compile-prod]
# [skip utest-both]
# [skip utest-debug]
# [skip utest-prod]
# [skip analysis]
# [skip coverage]
# [skip docs]
#
# --------------------------------------------------------------------

name: Branch Build
run-name: Branch Build ${{ github.event.head_commit.message }}

on:
  push:
    branches-ignore:
      - main
      - master

jobs:

  Build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip all]')"

    steps:
      - name: Install podman
        run: sudo apt install -y podman

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build debug
        if: "!contains(github.event.head_commit.message, '[skip compile-both]') && \
             !contains(github.event.head_commit.message, '[skip compile-debug]')"
        run: make debug

      - name: Run unit tests on debug
        if: "!contains(github.event.head_commit.message, '[skip compile-both]') && \
             !contains(github.event.head_commit.message, '[skip compile-debug]') && \
             !contains(github.event.head_commit.message, '[skip compile-utest-both]') && \
             !contains(github.event.head_commit.message, '[skip compile-utest-debug]')"
        run: make unit-test-debug

      - name: Build prod
        if: "!contains(github.event.head_commit.message, '[skip compile-both]') && \
             !contains(github.event.head_commit.message, '[skip compile-prod]')"
        run: make prod

      - name: Run unit tests on prod
        if: "!contains(github.event.head_commit.message, '[skip compile-both]') && \
             !contains(github.event.head_commit.message, '[skip compile-prod]') && \
             !contains(github.event.head_commit.message, '[skip compile-utest-both]') && \
             !contains(github.event.head_commit.message, '[skip compile-utest-prod]')"
        run: make unit-test-prod

      - name: Run static analysis
        if: "!contains(github.event.head_commit.message, '[skip analysis]')"
        run: make static-analysis

      - name: Run code coverage
        if: "!contains(github.event.head_commit.message, '[skip coverage]')"
        run: make code-coverage

      - name: Build docs
        if: "!contains(github.event.head_commit.message, '[skip docs]')"
        run: make docs
