# ----------------------------------------------
#
# Build main/master as a CM build.
# No steps can be skipped.
#
# ----------------------------------------------

name: CI Build
run-name: CI Build ${{ github.event.head_commit.message }}

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - docs/site/**
      
  # Allow manually triggering from GitHub Actions tab
  workflow_dispatch:
    
permissions:
  contents-write: write
# repository-projects: write
  
jobs:

  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Install podman
        run: sudo apt install -y podman
        
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Build debug
        run: make debug
        
      - name: Run unit tests on debug 
        run: make unit-test-debug
        
      - name: Build prod
        run: make prod
        
      - name: Run unit tests on prod 
        run: make unit-test-prod
        
      - name: Run static analysis
        run: make static-analysis
        
      - name: Preserve debug tree
        run: |
          mkdir -p _build/tmp-save-debug/
          cp -r _build/debug _build/tmp-save-debug/
          
      - name: Run code coverage
        run: make code-coverage
        
      - name: Restore debug tree
        run: |
          cp -r _build/tmp-save-debug/debug _build/
          rm -rf _build/tmp-save-debug

      - name: Build docs
        # Now that code-coverage and static-analysis have been
        # run, it's ok to make docs, which will pick up latest 
        # code-coverage and static analysis. This populates
        # _build/site.
        run: make docs

      - name: Publish docs
        # This copies _build/site to docs/site and performs a git
        # checkin. Hence we need the paths-ignore specification
        # above to prevent a build loop.
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name ${{ github.actor }}
          make docs-publish
          git push
