name: Build

on:
  push:
    branches:
      - main
      - master
      - trybuild

  # Allow manually triggering from GitHub Actions tab
  workflow_dispatch:

env:
  # On desktop, in container, whoami is "root" and HOME is /root.
  # On GitHub,  in container, whoami is "root" and HOME is /github/home.
  # Therefore build process can't find conan profile in /root/.conan2
  # Directly setting HOME ourselves solves this. Might create other
  # problems later - don't know, we'll see.
  CONAN_HOME: /root/.conan2

jobs:

  container-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kingsolomon1954/containers/gcc14-tools:14.2.0
      volumes:
        - ${{github.workspace}}:/work
      options: --cpus 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Indicate safe directory
        run: git config --global --add safe.directory /__w/cpp-bootstrap/cpp-bootstrap
      - name: Build debug and prod
        run: make NO_BLD_CNTR=1 both
      - name: Run unit tests
        run: make NO_BLD_CNTR=1 unit-test-both
